name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日自動更新
  workflow_dispatch:  # 手動実行もできる

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate
    steps:
      - uses: actions/checkout@v3
      - name: GitHub-Profile-Summary-Cards
        uses: vn7n24fzkq/github-profile-summary-cards@v0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
